;-------------------------------- PrivateDial ----------------------------------
; Filename: pjsip_endpoint.conf
; This file is an Asterisk configuration file, part of the PrivateDial suite.
; It is included by the pjsip_wizard.conf file
;

;-------------------------------- templates ------------------------------------

[w_term:local](!,w_term_i)
endpoint/allow = !all,ulaw,alaw
endpoint/callerid = Voicebot Test <1000>

;-------------------------------- sip terminals --------------------------------

[voicebot](w_term:local)
hint_exten = 1000
inbound_auth/username = voicebot
inbound_auth/password = voicebot
